In [1]:
import pandas as pd
import numpy as np

In [4]:
nba_data = pd.read_csv("season_stats.txt", header=1)

In [5]:
nba_data

,Rk,G,Date,Unnamed: 3,Opp,W/L,Tm,Opp.1,FG,FGA,...,FT.1,FTA.1,FT%.1,ORB.1,TRB.1,AST.1,STL.1,BLK.1,TOV.1,PF.1
0,1,1,2019-10-23,NaN,SAC,W,124,95,49,98,...,17,26,0.654,12,47,17,5,5,26,24
1,2,2,2019-10-25,@,DEN,L,107,108,34,86,...,29,36,0.806,8,45,21,7,12,14,26
2,3,3,2019-10-26,NaN,LAC,W,130,122,43,86,...,31,39,0.795,10,41,20,8,4,12,32
3,4,4,2019-10-28,NaN,UTA,L,95,96,33,80,...,32,39,0.821,6,49,19,8,5,23,26
4,5,5,2019-10-30,@,GSW,W,121,110,44,96,...,30,36,0.833,7,43,24,8,6,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,64,64,2020-03-08,NaN,MIL,W,140,131,47,85,...,16,21,0.762,7,36,23,7,3,10,29
64,65,65,2020-03-10,@,POR,L,105,121,35,87,...,14,17,0.824,9,46,20,9,9,11,17
65,66,66,2020-07-31,@,WAS,W,125,112,42,80,...,20,23,0.870,8,36,18,7,2,18,26
66,67,67,2020-08-02,NaN,DAL,W,117,115,42,93,...,33,37,0.892,10,49,22,8,5,8,22
67,68,68,2020-08-04,@,LAC,W,117,115,45,96,...,23,27,0.852,8,48,21,2,3,10,16